const DEFAULT_DATA={brand:{name:"aura.",announcement:"FREE shipping above IDR 700.000 🌿",about:"aura. is dedicated to bring the highest quality, clean, and natural perfume to you."},hero:{title:"Smell Like You Mean It.",subtitle:"Fragrances crafted for your story.",image:"https://images.unsplash.com/photo-1541643600914-78b084683702?w=1200&q=80",cta:"Explore Collection"},sections:{featuredTitle:"Play with Fragrance",featuredDesc:"Our fragrances can be worn individually or layered — that's what makes us special.",tryTitle:"Try First",tryDesc:"Try our Scent Designer Kit before committing to a full bottle.",press:["VOGUE","FIMELA","COSMOPOLITAN","ELLE"]},products:[{id:1,name:"Floraison",price:401000,originalPrice:0,category:"feminine",badge:"",image:"https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&q=80",description:"Modern yet timeless. This classic bouquet states romance and beauty with modern boldness.",notes:["Peony","Rose Otto","Lychee","Pink Pepper","White Musk","Patchouli"],vibe:"Vacation oasis near the ocean.",tune:"El Shaddai - Dylan Sin",stock:true},{id:2,name:"Lucid Dreams",price:401000,originalPrice:0,category:"feminine",badge:"Sold out",image:"https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?w=600&q=80",description:"A dreamy, ethereal scent for those who wander between reality and fantasy.",notes:["Iris","Violet","Sandalwood","Ambergris","Bergamot","Cashmere"],vibe:"A midnight walk through a moonlit garden.",tune:"Lucid Dreams - Juice WRLD",stock:false},{id:3,name:"Old Money",price:450000,originalPrice:0,category:"masculine",badge:"NEW",image:"https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80",description:"Rich and commanding. The scent of polished leather and oak.",notes:["Vetiver","Oakmoss","Leather","Tobacco","Amber","Cedar"],vibe:"A boardroom that smells like legacy.",tune:"Money Trees - Kendrick Lamar",stock:true},{id:4,name:"Dusk Reverie",price:401000,originalPrice:0,category:"masculine",badge:"",image:"https://images.unsplash.com/photo-1547887538-047f814a8854?w=600&q=80",description:"Warm and smoky, like the last light of a summer evening.",notes:["Oud","Cardamom","Saffron","Vanilla","Incense","Musk"],vibe:"Golden hour, forever.",tune:"Sunset Lover - Petit Biscuit",stock:true},{id:5,name:"Layering Bundle",price:495000,originalPrice:560000,category:"all",badge:"BEST VALUE",image:"https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=600&q=80",description:"7 travel-size scents in a designer case. Mix and match your signature.",notes:["All 7 scents included"],vibe:"Your scent, your rules.",tune:"Various",stock:true}],testimonials:[{name:"Annisa R.",rating:5,text:"Wanginya mewah banget hampir semua variant saya suka!",date:"March 2025"},{name:"Budi S.",rating:5,text:"Old Money is bold yet sophisticated. Got so many compliments!",date:"April 2025"}]};

const DataManager={get(){try{const s=localStorage.getItem('aura_data');return s?JSON.parse(s):JSON.parse(JSON.stringify(DEFAULT_DATA));}catch{return JSON.parse(JSON.stringify(DEFAULT_DATA));}},save(d){localStorage.setItem('aura_data',JSON.stringify(d));},reset(){localStorage.removeItem('aura_data');return JSON.parse(JSON.stringify(DEFAULT_DATA));}};

const Cart={get(){try{return JSON.parse(localStorage.getItem('aura_cart')||'[]');}catch{return[];}},save(c){localStorage.setItem('aura_cart',JSON.stringify(c));},add(id,qty=1){const p=DataManager.get().products.find(p=>p.id===id);if(!p||!p.stock)return false;const c=this.get();const ex=c.find(i=>i.id===id);if(ex)ex.qty+=qty;else c.push({id,qty});this.save(c);this.badge();return true;},remove(id){this.save(this.get().filter(i=>i.id!==id));this.badge();},count(){return this.get().reduce((s,i)=>s+i.qty,0);},total(){const d=DataManager.get();return this.get().reduce((s,i)=>{const p=d.products.find(p=>p.id===i.id);return s+(p?p.price*i.qty:0);},0);},badge(){const b=document.getElementById('cart-count');if(!b)return;const n=this.count();b.textContent=n;b.style.display=n>0?'flex':'none';}};

const fmt=n=>n.toLocaleString('id-ID');

function renderCartPanel(){const el=document.getElementById('cart-items');const tot=document.getElementById('cart-total');if(!el)return;const d=DataManager.get();const c=Cart.get();if(c.length===0){el.innerHTML='<div class="cart-empty"><p>Your cart is empty.</p><a href="shop.html" class="btn btn-dark" style="margin-top:1rem;display:inline-block">Shop Now</a></div>';}else{el.innerHTML=c.map(item=>{const p=d.products.find(p=>p.id===item.id);if(!p)return'';return`<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div class="ci-info"><strong>${p.name}</strong><span>IDR ${fmt(p.price)} x ${item.qty}</span></div><button onclick="Cart.remove(${p.id});renderCartPanel()">x</button></div>`;}).join('');}if(tot)tot.textContent=fmt(Cart.total());}

function addToCart(id){if(Cart.add(id)){showToast('Added to cart!');renderCartPanel();document.getElementById('cart-sidebar')?.classList.add('open');document.getElementById('cart-overlay')?.classList.add('open');}else showToast('Item is sold out.','error');}

function showToast(msg,t='ok'){const el=document.createElement('div');el.className='toast'+(t==='error'?' toast-error':'');el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.classList.add('show'),10);setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),300);},2500);}

document.addEventListener('DOMContentLoaded',()=>{Cart.badge();const d=DataManager.get();document.querySelectorAll('[data-ann]').forEach(el=>el.textContent=d.brand.announcement);document.querySelectorAll('[data-brand]').forEach(el=>el.textContent=d.brand.name);document.getElementById('hamburger')?.addEventListener('click',()=>document.getElementById('mobile-nav')?.classList.add('open'));document.getElementById('nav-close')?.addEventListener('click',()=>document.getElementById('mobile-nav')?.classList.remove('open'));document.getElementById('mobile-nav')?.addEventListener('click',e=>{if(e.target.id==='mobile-nav')e.target.classList.remove('open');});document.getElementById('cart-icon')?.addEventListener('click',()=>{renderCartPanel();document.getElementById('cart-sidebar')?.classList.add('open');document.getElementById('cart-overlay')?.classList.add('open');});document.getElementById('close-cart')?.addEventListener('click',()=>{document.getElementById('cart-sidebar')?.classList.remove('open');document.getElementById('cart-overlay')?.classList.remove('open');});document.getElementById('cart-overlay')?.addEventListener('click',()=>{document.getElementById('cart-sidebar')?.classList.remove('open');document.getElementById('cart-overlay')?.classList.remove('open');});const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible');}),{threshold:0.1});document.querySelectorAll('.fade-in').forEach(el=>obs.observe(el));});
